kind: Deployment
apiVersion: apps/v1
metadata:
  name: celery-beat
  namespace: zippedscript-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: registry.digitalocean.com/production/api:latest-pre
          command:
            - poetry
            - run
            - celery
            - '-A'
            - core
            - beat
            - '--loglevel=info'
            - '--scheduler'
            - django_celery_beat.schedulers:DatabaseScheduler
          envFrom:
            - secretRef:
                name: api-secret
            - configMapRef:
                name: apo-config
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: production
